// <auto-generated>
// 由 DataTableGenerator 生成，请勿手动修改
// </auto-generated>

using System.Collections.Generic;
using Newtonsoft.Json;

public sealed class BossPhaseConfigRow
{
    /// <summary>对应 EnemyConfig.EnemyId</summary>
    public string BossId { get; set; }
    /// <summary>阶段编号：1 / 2 / 3</summary>
    public int PhaseIndex { get; set; }
    /// <summary>进入本阶段的 HP 百分比：1.0=满血，0.6=60%HP</summary>
    public float HPThreshold { get; set; }
    /// <summary>本阶段解锁技能 ID，逗号分隔，叠加不替换</summary>
    public string NewSkillIds { get; set; }
    /// <summary>本阶段伤害倍率，1.0=无变化</summary>
    public float EnrageMultiplier { get; set; }
    /// <summary>阶段转换特效 ID</summary>
    public string PhaseVFXId { get; set; }
    /// <summary>阶段 BGM cue ID</summary>
    public string PhaseBGMCueId { get; set; }
    /// <summary>v2.1 新增：Boss 死亡时必掉的主题配方 ID（仅 PhaseIndex=3 有效，其余填空）</summary>
    public string DeathPatternRecipeId { get; set; }
}

public sealed class BossPhaseConfig : IDataTable
{
    // 复合键：BossId + PhaseIndex
    readonly Dictionary<string, BossPhaseConfigRow> _rows = new();

    public void Load(string json)
    {
        var file = JsonConvert.DeserializeObject<DataTableFile<BossPhaseConfigRow>>(json);
        _rows.Clear();
        foreach (var row in file.rows)
        {
            string key = MakeKey(row.BossId, row.PhaseIndex);
            _rows[key] = row;
        }
    }

    static string MakeKey(string bossId, int phase) => $"{bossId}_{phase}";

    public BossPhaseConfigRow GetByBossPhase(string bossId, int phase)
    {
        string key = MakeKey(bossId, phase);
        if (_rows.TryGetValue(key, out var row))
            return row;
        throw new KeyNotFoundException($"BossPhaseConfig 未找到 BossId={bossId} Phase={phase}");
    }

    public bool TryGetByBossPhase(string bossId, int phase, out BossPhaseConfigRow row)
        => _rows.TryGetValue(MakeKey(bossId, phase), out row);

    public IReadOnlyDictionary<string, BossPhaseConfigRow> All => _rows;
}
