// <auto-generated>
// 由 DataTableGenerator 生成，请勿手动修改
// </auto-generated>

using System;

public static class DataTableRegistry
{
    public static readonly DataTableEntry[] Entries =
    {
        new DataTableEntry("ResourceConfig", typeof(ResourceConfig)),
        new DataTableEntry("TattooPartConfig", typeof(TattooPartConfig)),
        new DataTableEntry("TattooColorConfig", typeof(TattooColorConfig)),
        new DataTableEntry("TattooPatternConfig", typeof(TattooPatternConfig)),
        new DataTableEntry("TattooElementConfig", typeof(TattooElementConfig)),
        new DataTableEntry("TattooShapeConfig", typeof(TattooShapeConfig)),
    };
}

public readonly struct DataTableEntry
{
    public readonly string FileName;
    public readonly Type TableType;

    public DataTableEntry(string fileName, Type tableType)
    {
        FileName = fileName;
        TableType = tableType;
    }
}
