// <auto-generated>
// 由 DataTableGenerator 生成，请勿手动修改
// </auto-generated>

using System.Collections.Generic;
using Newtonsoft.Json;

public sealed class FeatureInjectionConfigRow
{
    /// <summary>特征主键</summary>
    public int Id { get; set; }
    /// <summary>特征名</summary>
    public string FeatureName { get; set; }
    /// <summary>覆盖的 TerrainType Id</summary>
    public int TerrainType { get; set; }
    /// <summary>Line / Blob</summary>
    public string SpreadMode { get; set; }
    /// <summary>每图最少实例数</summary>
    public int CountMin { get; set; }
    /// <summary>每图最多实例数</summary>
    public int CountMax { get; set; }
    /// <summary>单实例最小格数/长度</summary>
    public int SizeMin { get; set; }
    /// <summary>单实例最大格数/长度</summary>
    public int SizeMax { get; set; }
}

public sealed class FeatureInjectionConfig : IDataTable
{
    readonly Dictionary<int, FeatureInjectionConfigRow> _rows = new();

    public void Load(string json)
    {
        var file = JsonConvert.DeserializeObject<DataTableFile<FeatureInjectionConfigRow>>(json);
        _rows.Clear();
        foreach (var row in file.rows)
        {
            _rows[row.Id] = row;
        }
    }

    public FeatureInjectionConfigRow GetById(int id)
    {
        if (_rows.TryGetValue(id, out var row))
            return row;
        throw new KeyNotFoundException($"FeatureInjectionConfig 未找到 Id={id}");
    }

    public bool TryGetById(int id, out FeatureInjectionConfigRow row) => _rows.TryGetValue(id, out row);

    public IReadOnlyDictionary<int, FeatureInjectionConfigRow> All => _rows;
}
