// <auto-generated>
// 由 DataTableGenerator 生成，请勿手动修改
// </auto-generated>

using System.Collections.Generic;
using Newtonsoft.Json;

public sealed class FeaturePointConfigRow
{
    /// <summary>功能点主键</summary>
    public int Id { get; set; }
    /// <summary>Boss / Merchant / TattooStudio. Spawn is sampled separately.</summary>
    public string PointType { get; set; }
    /// <summary>是否每局必需</summary>
    public bool Required { get; set; }
    /// <summary>与其他功能点的最小距离，米</summary>
    public float MinSpacing { get; set; }
    /// <summary>离地图边界安全距离，米</summary>
    public float SafeMargin { get; set; }
    /// <summary>功能点落点偏好的 TerrainType Id</summary>
    public int PreferredTerrain { get; set; }
}

public sealed class FeaturePointConfig : IDataTable
{
    readonly Dictionary<int, FeaturePointConfigRow> _rows = new();

    public void Load(string json)
    {
        var file = JsonConvert.DeserializeObject<DataTableFile<FeaturePointConfigRow>>(json);
        _rows.Clear();
        foreach (var row in file.rows)
        {
            _rows[row.Id] = row;
        }
    }

    public FeaturePointConfigRow GetById(int id)
    {
        if (_rows.TryGetValue(id, out var row))
            return row;
        throw new KeyNotFoundException($"FeaturePointConfig 未找到 Id={id}");
    }

    public bool TryGetById(int id, out FeaturePointConfigRow row) => _rows.TryGetValue(id, out row);

    public IReadOnlyDictionary<int, FeaturePointConfigRow> All => _rows;
}
