// <auto-generated>
// 由 DataTableGenerator 生成，请勿手动修改
// </auto-generated>

using System.Collections.Generic;
using Newtonsoft.Json;

public sealed class MapTemplateConfigRow
{
    /// <summary>主题模板主键（1=AI_RUINS, 2=CYBERPUNK, 3=MAGITECH）</summary>
    public int Id { get; set; }
    /// <summary>主题枚举名（AI_RUINS / CYBERPUNK / MAGITECH）</summary>
    public string ThemeName { get; set; }
    /// <summary>v2.1 地图根边界尺寸（单位 m，固定 150）</summary>
    public float MapSize { get; set; }
    /// <summary>BSP 最小房间尺寸（单位 m）</summary>
    public float MinRoomSize { get; set; }
    /// <summary>BSP 最大递归深度（v2.1 = 4）</summary>
    public int BspMaxDepth { get; set; }
    /// <summary>地块池 ID，用于 tile 替换。MVP 暂未消费</summary>
    public int TerrainPoolId { get; set; }
    /// <summary>房间 Prefab 路径前缀（相对 Resources/Prefab/Map/）。MVP 留空</summary>
    public string PrefabPath { get; set; }
    /// <summary>HUD 强调色（hex，如 #66CCFF）。透传字段</summary>
    public string HudAccentColor { get; set; }
    /// <summary>主色调（hex）。透传字段</summary>
    public string DominantColor { get; set; }
}

public sealed class MapTemplateConfig : IDataTable
{
    readonly Dictionary<int, MapTemplateConfigRow> _rows = new();

    public void Load(string json)
    {
        var file = JsonConvert.DeserializeObject<DataTableFile<MapTemplateConfigRow>>(json);
        _rows.Clear();
        foreach (var row in file.rows)
        {
            _rows[row.Id] = row;
        }
    }

    public MapTemplateConfigRow GetById(int id)
    {
        if (_rows.TryGetValue(id, out var row))
            return row;
        throw new KeyNotFoundException($"MapTemplateConfig 未找到 Id={id}");
    }

    public bool TryGetById(int id, out MapTemplateConfigRow row) => _rows.TryGetValue(id, out row);

    public IReadOnlyDictionary<int, MapTemplateConfigRow> All => _rows;
}
