// <auto-generated>
// 由 DataTableGenerator 生成，请勿手动修改
// </auto-generated>

using System.Collections.Generic;
using Newtonsoft.Json;

public sealed class NPCConfigRow
{
    /// <summary>主键，运行时索引</summary>
    public int Id { get; set; }
    /// <summary>实例唯一字符串 ID（如 tattooist_default）</summary>
    public string NPCId { get; set; }
    /// <summary>Tattooist | Merchant</summary>
    public string Type { get; set; }
    /// <summary>适用地图主题：All / Slum / Lab / Alien</summary>
    public string MapTheme { get; set; }
    /// <summary>主题价格倍率（普通 1.0 / 实验室 1.1 / 外星 1.2）</summary>
    public float ThemePriceMul { get; set; }
    /// <summary>关联 ShopStockConfig 中的 TableId；纹身师留空字符串</summary>
    public string ShopStockTable { get; set; }
    /// <summary>触发交互提示距离（m）</summary>
    public float InteractRadius { get; set; }
    /// <summary>警卫怪巡逻半径（m）</summary>
    public float GuardRadius { get; set; }
    /// <summary>被攻击后关闭服务时长（s）</summary>
    public float ServiceCooldown { get; set; }
    /// <summary>被攻击时生成的警卫怪 PrefabId</summary>
    public string GuardSpawnId { get; set; }
    /// <summary>首次警告警卫数量</summary>
    public int GuardCount1 { get; set; }
    /// <summary>升级警告警卫数量</summary>
    public int GuardCount2 { get; set; }
}

public sealed class NPCConfig : IDataTable
{
    readonly Dictionary<int, NPCConfigRow> _rows = new();

    public void Load(string json)
    {
        var file = JsonConvert.DeserializeObject<DataTableFile<NPCConfigRow>>(json);
        _rows.Clear();
        foreach (var row in file.rows)
        {
            _rows[row.Id] = row;
        }
    }

    public NPCConfigRow GetById(int id)
    {
        if (_rows.TryGetValue(id, out var row))
            return row;
        throw new KeyNotFoundException($"NPCConfig 未找到 Id={id}");
    }

    public bool TryGetById(int id, out NPCConfigRow row) => _rows.TryGetValue(id, out row);

    public IReadOnlyDictionary<int, NPCConfigRow> All => _rows;
}
