// <auto-generated>
// 由 DataTableGenerator 生成，请勿手动修改
// </auto-generated>

using System.Collections.Generic;
using Newtonsoft.Json;

public sealed class ProjectileConfigRow
{
    /// <summary>主键，与 WeaponConfig.ProjectileId 关联</summary>
    public string ProjectileId { get; set; }
    /// <summary>飞行速度 (m/s)</summary>
    public float Speed { get; set; }
    /// <summary>最大飞行距离，超出后回池 (m)</summary>
    public float MaxRange { get; set; }
    /// <summary>true=穿透，命中后继续飞行可触发多次 AttackHitEvent</summary>
    public bool Piercing { get; set; }
    /// <summary>>0=着弹点范围判定半径 (m)</summary>
    public float AoeRadius { get; set; }
    /// <summary>Resources/Prefabs/Projectiles/ 下的 Prefab 路径名</summary>
    public string VisualPrefabPath { get; set; }
    /// <summary>对象池预分配容量</summary>
    public int PoolSize { get; set; }
}

public sealed class ProjectileConfig : IDataTable
{
    readonly Dictionary<string, ProjectileConfigRow> _rows = new();

    public void Load(string json)
    {
        var file = JsonConvert.DeserializeObject<DataTableFile<ProjectileConfigRow>>(json);
        _rows.Clear();
        foreach (var row in file.rows)
        {
            _rows[row.ProjectileId] = row;
        }
    }

    public ProjectileConfigRow GetById(string projectileId)
    {
        if (_rows.TryGetValue(projectileId, out var row))
            return row;
        throw new KeyNotFoundException($"ProjectileConfig 未找到 ProjectileId={projectileId}");
    }

    public bool TryGetById(string projectileId, out ProjectileConfigRow row) =>
        _rows.TryGetValue(projectileId, out row);

    public IReadOnlyDictionary<string, ProjectileConfigRow> All => _rows;
}
