// <auto-generated>
// 由 DataTableGenerator 生成，请勿手动修改
// </auto-generated>

using System.Collections.Generic;
using Newtonsoft.Json;

public sealed class ResourceConfigRow
{
    /// <summary>资源ID，主键</summary>
    public int Id { get; set; }
    /// <summary>资源标识名，便于阅读</summary>
    public string Name { get; set; }
    /// <summary>资源类型，对应Resources下子文件夹名（Animation/Audio/Effect/Font/Material/Model/Prefab/Sprite/Texture）</summary>
    public string Type { get; set; }
    /// <summary>相对Resources/{Type}/的加载路径，不含扩展名</summary>
    public string LoadPath { get; set; }
}

public sealed class ResourceConfig : IDataTable
{
    readonly Dictionary<int, ResourceConfigRow> _rows = new();

    public void Load(string json)
    {
        var file = JsonConvert.DeserializeObject<DataTableFile<ResourceConfigRow>>(json);
        _rows.Clear();
        foreach (var row in file.rows)
        {
            _rows[row.Id] = row;
        }
    }

    public ResourceConfigRow GetById(int id)
    {
        if (_rows.TryGetValue(id, out var row))
            return row;
        throw new KeyNotFoundException($"ResourceConfig 未找到 Id={id}");
    }

    public bool TryGetById(int id, out ResourceConfigRow row) => _rows.TryGetValue(id, out row);

    public IReadOnlyDictionary<int, ResourceConfigRow> All => _rows;
}
