// <auto-generated>
// 由 DataTableGenerator 生成，请勿手动修改
// </auto-generated>

using System.Collections.Generic;
using Newtonsoft.Json;

public sealed class ShopStockConfigRow
{
    /// <summary>主键</summary>
    public int Id { get; set; }
    /// <summary>被 NPCConfig.ShopStockTable 引用的表段 ID</summary>
    public string TableId { get; set; }
    /// <summary>物品 ID</summary>
    public int ItemId { get; set; }
    /// <summary>Weapon / Skill / Ink / Antidote / Remover / RareInk</summary>
    public string Category { get; set; }
    /// <summary>同 TableId 内归一化抽取权重</summary>
    public float Weight { get; set; }
    /// <summary>本局库存最小数量</summary>
    public int MinCount { get; set; }
    /// <summary>本局库存最大数量</summary>
    public int MaxCount { get; set; }
    /// <summary>基础售价（× ThemePriceMul = 实际售价）</summary>
    public int BasePrice { get; set; }
    /// <summary>玩家出售回收比例（× BasePrice）</summary>
    public float SellRatio { get; set; }
}

public sealed class ShopStockConfig : IDataTable
{
    readonly Dictionary<int, ShopStockConfigRow> _rows = new();

    public void Load(string json)
    {
        var file = JsonConvert.DeserializeObject<DataTableFile<ShopStockConfigRow>>(json);
        _rows.Clear();
        foreach (var row in file.rows)
        {
            _rows[row.Id] = row;
        }
    }

    public ShopStockConfigRow GetById(int id)
    {
        if (_rows.TryGetValue(id, out var row))
            return row;
        throw new KeyNotFoundException($"ShopStockConfig 未找到 Id={id}");
    }

    public bool TryGetById(int id, out ShopStockConfigRow row) => _rows.TryGetValue(id, out row);

    public IReadOnlyDictionary<int, ShopStockConfigRow> All => _rows;
}
