// <auto-generated>
// 由 DataTableGenerator 生成，请勿手动修改
// </auto-generated>

using System.Collections.Generic;
using Newtonsoft.Json;

public sealed class TattooElementConfigRow
{
    /// <summary>主键 1-7</summary>
    public int Id { get; set; }
    /// <summary>Fire / Lightning / Nature / Frost / Mutation / Holy / Pure</summary>
    public string Name { get; set; }
    /// <summary>元素基础倍率</summary>
    public float BaseMultiplier { get; set; }
    /// <summary>元素参数 1（Fire: BurnDPS / Frost: SlowFactor / Holy: HealPercent / Pure: MagnitudeBonus / Lightning: ParalyzeDuration / Nature: PoisonDPS）</summary>
    public float Param1 { get; set; }
    /// <summary>元素参数 2（Fire: BurnDuration / Frost: SlowDuration / Pure: FocusStackBonus / Nature: PoisonDuration）</summary>
    public float Param2 { get; set; }
    /// <summary>元素参数 3（Frost/Pure: 最大叠层数；Mutation: 随机种子）</summary>
    public float Param3 { get; set; }
}

public sealed class TattooElementConfig : IDataTable
{
    readonly Dictionary<int, TattooElementConfigRow> _rows = new();

    public void Load(string json)
    {
        var file = JsonConvert.DeserializeObject<DataTableFile<TattooElementConfigRow>>(json);
        _rows.Clear();
        foreach (var row in file.rows)
        {
            _rows[row.Id] = row;
        }
    }

    public TattooElementConfigRow GetById(int id)
    {
        if (_rows.TryGetValue(id, out var row))
            return row;
        throw new KeyNotFoundException($"TattooElementConfig 未找到 Id={id}");
    }

    public bool TryGetById(int id, out TattooElementConfigRow row) => _rows.TryGetValue(id, out row);

    public IReadOnlyDictionary<int, TattooElementConfigRow> All => _rows;
}
