// <auto-generated>
// 由 DataTableGenerator 生成，请勿手动修改
// </auto-generated>

using System.Collections.Generic;
using Newtonsoft.Json;

public sealed class TattooEnchantRecipeConfigRow
{
    /// <summary>主键</summary>
    public int Id { get; set; }
    /// <summary>颜料档：Common / Rare / Legendary</summary>
    public string ColorTier { get; set; }
    /// <summary>附魔金币花费</summary>
    public int CoinCost { get; set; }
    /// <summary>附魔稀有颜料花费（固定 1 瓶）</summary>
    public int RarePigmentCost { get; set; }
    /// <summary>每个纹身槽最大词缀数（固定 2）</summary>
    public int MaxAffixPerSlot { get; set; }
}

public sealed class TattooEnchantRecipeConfig : IDataTable
{
    readonly Dictionary<int, TattooEnchantRecipeConfigRow> _rows = new();

    public void Load(string json)
    {
        var file = JsonConvert.DeserializeObject<DataTableFile<TattooEnchantRecipeConfigRow>>(json);
        _rows.Clear();
        foreach (var row in file.rows)
        {
            _rows[row.Id] = row;
        }
    }

    public TattooEnchantRecipeConfigRow GetById(int id)
    {
        if (_rows.TryGetValue(id, out var row))
            return row;
        throw new KeyNotFoundException($"TattooEnchantRecipeConfig 未找到 Id={id}");
    }

    public bool TryGetById(int id, out TattooEnchantRecipeConfigRow row) => _rows.TryGetValue(id, out row);

    public IReadOnlyDictionary<int, TattooEnchantRecipeConfigRow> All => _rows;

    /// <summary>按 ColorTier 字符串查找配方行（NPCModule 用）。</summary>
    public bool TryGetByColorTier(string colorTier, out TattooEnchantRecipeConfigRow row)
    {
        foreach (var r in _rows.Values)
        {
            if (r.ColorTier == colorTier)
            {
                row = r;
                return true;
            }
        }
        row = null;
        return false;
    }
}
