// <auto-generated>
// 由 DataTableGenerator 生成，请勿手动修改
// </auto-generated>

using System.Collections.Generic;
using Newtonsoft.Json;

public sealed class TattooColorConfigRow
{
    /// <summary>主键 1-7</summary>
    public int Id { get; set; }
    /// <summary>Red / Yellow / Green / Blue / Purple / Gold / White</summary>
    public string Name { get; set; }
    /// <summary>ElementType enum 名：Fire / Lightning / Nature / Frost / Mutation / Holy / Pure</summary>
    public string Element { get; set; }
    /// <summary>颜色级倍率（基础 1.0）</summary>
    public float ColorMultiplier { get; set; }
}

public sealed class TattooColorConfig : IDataTable
{
    readonly Dictionary<int, TattooColorConfigRow> _rows = new();

    public void Load(string json)
    {
        var file = JsonConvert.DeserializeObject<DataTableFile<TattooColorConfigRow>>(json);
        _rows.Clear();
        foreach (var row in file.rows)
        {
            _rows[row.Id] = row;
        }
    }

    public TattooColorConfigRow GetById(int id)
    {
        if (_rows.TryGetValue(id, out var row))
            return row;
        throw new KeyNotFoundException($"TattooColorConfig 未找到 Id={id}");
    }

    public bool TryGetById(int id, out TattooColorConfigRow row) => _rows.TryGetValue(id, out row);

    public IReadOnlyDictionary<int, TattooColorConfigRow> All => _rows;
}
