// <auto-generated>
// 由 DataTableGenerator 生成，请勿手动修改
// </auto-generated>

using System.Collections.Generic;
using Newtonsoft.Json;

public sealed class TattooShapeConfigRow
{
    /// <summary>主键 1-8</summary>
    public int Id { get; set; }
    /// <summary>ShapeBehavior 名</summary>
    public string Name { get; set; }
    /// <summary>形状参数 1（AOEBurst: AreaFactor / StackingMark: Threshold / MultiHit: Segments / ChainJump: MaxJumps / ProbBurst: Probability / TrailZone: TickFactor / SummonForm: SummonMultiplier）</summary>
    public float Param1 { get; set; }
    /// <summary>形状参数 2（AOEBurst: MaxTargets / StackingMark: BurstMul / ChainJump: Decay / ProbBurst: BurstMultiplier / TrailZone: Ticks）</summary>
    public float Param2 { get; set; }
    /// <summary>形状参数 3（ProbBurst: Seed）</summary>
    public float Param3 { get; set; }
}

public sealed class TattooShapeConfig : IDataTable
{
    readonly Dictionary<int, TattooShapeConfigRow> _rows = new();

    public void Load(string json)
    {
        var file = JsonConvert.DeserializeObject<DataTableFile<TattooShapeConfigRow>>(json);
        _rows.Clear();
        foreach (var row in file.rows)
        {
            _rows[row.Id] = row;
        }
    }

    public TattooShapeConfigRow GetById(int id)
    {
        if (_rows.TryGetValue(id, out var row))
            return row;
        throw new KeyNotFoundException($"TattooShapeConfig 未找到 Id={id}");
    }

    public bool TryGetById(int id, out TattooShapeConfigRow row) => _rows.TryGetValue(id, out row);

    public IReadOnlyDictionary<int, TattooShapeConfigRow> All => _rows;
}
