// <auto-generated>
// 由 DataTableGenerator 生成，请勿手动修改
// </auto-generated>

using System.Collections.Generic;
using Newtonsoft.Json;

public sealed class TattooElementConfigRow
{
    /// <summary>主键 1-7</summary>
    public int Id { get; set; }
    /// <summary>Fire / Lightning / Nature / Frost / Mutation / Holy / Pure</summary>
    public string Name { get; set; }
    /// <summary>元素基础倍率</summary>
    public float BaseMultiplier { get; set; }
    /// <summary>元素参数 1</summary>
    public float Param1 { get; set; }
    /// <summary>元素参数 2</summary>
    public float Param2 { get; set; }
    /// <summary>元素参数 3</summary>
    public float Param3 { get; set; }
}

public sealed class TattooElementConfig : IDataTable
{
    readonly Dictionary<int, TattooElementConfigRow> _rows = new();
    readonly Dictionary<string, TattooElementConfigRow> _rowsByName = new();

    public void Load(string json)
    {
        var file = JsonConvert.DeserializeObject<DataTableFile<TattooElementConfigRow>>(json);
        _rows.Clear();
        _rowsByName.Clear();
        foreach (var row in file.rows)
        {
            _rows[row.Id] = row;
            _rowsByName[row.Name] = row;
        }
    }

    public TattooElementConfigRow GetById(int id)
    {
        if (_rows.TryGetValue(id, out var row))
            return row;
        throw new KeyNotFoundException($"TattooElementConfig 未找到 Id={id}");
    }

    public TattooElementConfigRow GetByName(string name)
    {
        if (_rowsByName.TryGetValue(name, out var row))
            return row;
        throw new KeyNotFoundException($"TattooElementConfig 未找到 Name={name}");
    }

    public bool TryGetById(int id, out TattooElementConfigRow row) => _rows.TryGetValue(id, out row);

    public IReadOnlyDictionary<int, TattooElementConfigRow> All => _rows;
}
