// <auto-generated>
// 由 DataTableGenerator 生成，请勿手动修改
// </auto-generated>

using System.Collections.Generic;
using Newtonsoft.Json;

public sealed class TattooPatternConfigRow
{
    /// <summary>主键 1-8</summary>
    public int Id { get; set; }
    /// <summary>Line / Ring / Spiral / Zigzag / Bolt / Star / Stream / Beast</summary>
    public string Name { get; set; }
    /// <summary>ShapeBehavior 名</summary>
    public string Shape { get; set; }
    /// <summary>图案级倍率</summary>
    public float PatternMultiplier { get; set; }
}

public sealed class TattooPatternConfig : IDataTable
{
    readonly Dictionary<int, TattooPatternConfigRow> _rows = new();

    public void Load(string json)
    {
        var file = JsonConvert.DeserializeObject<DataTableFile<TattooPatternConfigRow>>(json);
        _rows.Clear();
        foreach (var row in file.rows)
        {
            _rows[row.Id] = row;
        }
    }

    public TattooPatternConfigRow GetById(int id)
    {
        if (_rows.TryGetValue(id, out var row))
            return row;
        throw new KeyNotFoundException($"TattooPatternConfig 未找到 Id={id}");
    }

    public bool TryGetById(int id, out TattooPatternConfigRow row) => _rows.TryGetValue(id, out row);

    public IReadOnlyDictionary<int, TattooPatternConfigRow> All => _rows;
}
