// <auto-generated>
// 由 DataTableGenerator 生成，请勿手动修改
// </auto-generated>

using System.Collections.Generic;
using Newtonsoft.Json;

public sealed class TerrainAdjacencyRulesRow
{
    /// <summary>规则主键</summary>
    public int Id { get; set; }
    /// <summary>起始 TerrainType Id</summary>
    public int FromType { get; set; }
    /// <summary>相邻 TerrainType Id</summary>
    public int ToType { get; set; }
    /// <summary>是否允许 4 邻相接</summary>
    public bool Allowed { get; set; }
}

public sealed class TerrainAdjacencyRules : IDataTable
{
    readonly Dictionary<int, TerrainAdjacencyRulesRow> _rows = new();

    public void Load(string json)
    {
        var file = JsonConvert.DeserializeObject<DataTableFile<TerrainAdjacencyRulesRow>>(json);
        _rows.Clear();
        foreach (var row in file.rows)
        {
            _rows[row.Id] = row;
        }
    }

    public TerrainAdjacencyRulesRow GetById(int id)
    {
        if (_rows.TryGetValue(id, out var row))
            return row;
        throw new KeyNotFoundException($"TerrainAdjacencyRules 未找到 Id={id}");
    }

    public bool TryGetById(int id, out TerrainAdjacencyRulesRow row) => _rows.TryGetValue(id, out row);

    public IReadOnlyDictionary<int, TerrainAdjacencyRulesRow> All => _rows;
}
