// <auto-generated>
// 由 DataTableGenerator 生成，请勿手动修改
// </auto-generated>

using System.Collections.Generic;
using Newtonsoft.Json;

public sealed class TerrainTypeConfigRow
{
    /// <summary>TerrainType 枚举值</summary>
    public int Id { get; set; }
    /// <summary>地形名</summary>
    public string TypeName { get; set; }
    /// <summary>TerrainType 到 TileBase/资源键映射</summary>
    public string TileAssetKey { get; set; }
    /// <summary>是否可行走</summary>
    public bool IsWalkable { get; set; }
    /// <summary>地形移速倍率</summary>
    public float MoveSpeedMul { get; set; }
    /// <summary>区域生长权重</summary>
    public int GrowthWeight { get; set; }
    /// <summary>堵死降级时使用的泛化地形</summary>
    public bool IsFallback { get; set; }
}

public sealed class TerrainTypeConfig : IDataTable
{
    readonly Dictionary<int, TerrainTypeConfigRow> _rows = new();

    public void Load(string json)
    {
        var file = JsonConvert.DeserializeObject<DataTableFile<TerrainTypeConfigRow>>(json);
        _rows.Clear();
        foreach (var row in file.rows)
        {
            _rows[row.Id] = row;
        }
    }

    public TerrainTypeConfigRow GetById(int id)
    {
        if (_rows.TryGetValue(id, out var row))
            return row;
        throw new KeyNotFoundException($"TerrainTypeConfig 未找到 Id={id}");
    }

    public bool TryGetById(int id, out TerrainTypeConfigRow row) => _rows.TryGetValue(id, out row);

    public IReadOnlyDictionary<int, TerrainTypeConfigRow> All => _rows;
}
