// <auto-generated>
// 由 DataTableGenerator 生成，请勿手动修改
// </auto-generated>

using System.Collections.Generic;
using Newtonsoft.Json;

public sealed class ZoneShrinkConfigRow
{
    /// <summary>阶段 ID 即 Phase 编号（0/1/2）</summary>
    public int Id { get; set; }
    /// <summary>阶段名（Phase0_Slow / Phase1_Offset / Phase2_Rush）</summary>
    public string PhaseName { get; set; }
    /// <summary>本阶段进入时刻（秒，Run 启动 0 起）</summary>
    public float StartTime { get; set; }
    /// <summary>本阶段持续时长（秒）</summary>
    public float Duration { get; set; }
    /// <summary>本阶段结束时的目标半径（米）</summary>
    public float TargetRadius { get; set; }
    /// <summary>圈外伤害（HP/s）</summary>
    public float OutZoneDamage { get; set; }
    /// <summary>圈心偏移模式（None / Drift / Fixed），MVP 仅 None</summary>
    public string CenterOffsetMode { get; set; }
}

public sealed class ZoneShrinkConfig : IDataTable
{
    readonly Dictionary<int, ZoneShrinkConfigRow> _rows = new();

    public void Load(string json)
    {
        var file = JsonConvert.DeserializeObject<DataTableFile<ZoneShrinkConfigRow>>(json);
        _rows.Clear();
        foreach (var row in file.rows)
        {
            _rows[row.Id] = row;
        }
    }

    public ZoneShrinkConfigRow GetById(int id)
    {
        if (_rows.TryGetValue(id, out var row))
            return row;
        throw new KeyNotFoundException($"ZoneShrinkConfig 未找到 Id={id}");
    }

    public bool TryGetById(int id, out ZoneShrinkConfigRow row) => _rows.TryGetValue(id, out row);

    public IReadOnlyDictionary<int, ZoneShrinkConfigRow> All => _rows;
}
