// <auto-generated>
// 由 DataTableGenerator 生成，请勿手动修改
// </auto-generated>

using System.Collections.Generic;
using Newtonsoft.Json;

public sealed class ChestConfigRow
{
    /// <summary>宝箱类型主键，如 chest_common / chest_rare</summary>
    public string ChestId { get; set; }
    /// <summary>枚举：Weapon / Gold / Potion</summary>
    public string RewardType { get; set; }
    /// <summary>Weapon 时填 WeaponId（从 WeaponDropConfig 随机选）；Gold/Potion 时留空字符串</summary>
    public string RewardId { get; set; }
    /// <summary>Gold 时为金币数量（单位 coin）；Weapon 时恒为 1；Potion 时为药水数量</summary>
    public int RewardAmount { get; set; }
    /// <summary>同 ChestId 内概率（整数百分比），同 ChestId 所有行之和必须 = 100（DataTableModule Assert）</summary>
    public int Probability { get; set; }
}

public sealed class ChestConfig : IDataTable
{
    readonly List<ChestConfigRow> _rows = new();

    public void Load(string json)
    {
        var file = JsonConvert.DeserializeObject<DataTableFile<ChestConfigRow>>(json);
        _rows.Clear();
        foreach (var row in file.rows)
        {
            _rows.Add(row);
        }
    }

    /// <summary>取指定 ChestId 的所有奖励行（用于按 Probability 加权随机选择）。</summary>
    public IReadOnlyList<ChestConfigRow> GetByChestId(string chestId)
    {
        var list = new List<ChestConfigRow>();
        foreach (var row in _rows)
        {
            if (row.ChestId == chestId)
                list.Add(row);
        }
        return list;
    }

    public IReadOnlyList<ChestConfigRow> Rows => _rows;
}
