// <auto-generated>
// 由 DataTableGenerator 生成，请勿手动修改
// </auto-generated>

using System.Collections.Generic;
using Newtonsoft.Json;

public sealed class EnemyConfigRow
{
    /// <summary>怪物唯一 ID，如 enemy_ai_servo_light</summary>
    public string EnemyId { get; set; }
    /// <summary>本地化键，如 enemy.ai_servo</summary>
    public string DisplayName { get; set; }
    /// <summary>AI_RUINS | ALIEN_HIVE | VIRUS_SWAMP | common</summary>
    public string ThemeId { get; set; }
    /// <summary>Light | Elite | Boss</summary>
    public string Tier { get; set; }
    /// <summary>Run 第 0 分钟基础 HP</summary>
    public float BaseHP { get; set; }
    /// <summary>HP 线性增长系数，HP_t = BaseHP × (1 + K × t_min)</summary>
    public float HPCurveK { get; set; }
    /// <summary>基础攻击伤害 (point)</summary>
    public float BaseDamage { get; set; }
    /// <summary>伤害随时间增长系数</summary>
    public float DamageCurveK { get; set; }
    /// <summary>移动速度 (m/s)</summary>
    public float MoveSpeed { get; set; }
    /// <summary>攻击判定范围 (m)</summary>
    public float AttackRange { get; set; }
    /// <summary>感知半径 (m)；失追距离 = DetectRange × 2</summary>
    public float DetectRange { get; set; }
    /// <summary>技能 ID 逗号分隔；Light 通常空</summary>
    public string SkillIds { get; set; }
    /// <summary>随机掉落表 ID</summary>
    public string LootTableId { get; set; }
    /// <summary>v2.1 新增：必掉物品 ID 逗号分隔；Elite 必含稀有颜料 ID</summary>
    public string GuaranteedLootIds { get; set; }
    /// <summary>v2.1 新增：精英必掉稀有颜料标记；1=必掉，0=不掉</summary>
    public int ElitePaintDropRare { get; set; }
    /// <summary>击杀奖励 XP</summary>
    public int XPReward { get; set; }
    /// <summary>击杀掉落金币范围，格式 min-max</summary>
    public string CoinReward { get; set; }
    /// <summary>所属怪物池 ID，逗号分隔</summary>
    public string PoolIds { get; set; }
}

public sealed class EnemyConfig : IDataTable
{
    readonly Dictionary<string, EnemyConfigRow> _rows = new();

    public void Load(string json)
    {
        var file = JsonConvert.DeserializeObject<DataTableFile<EnemyConfigRow>>(json);
        _rows.Clear();
        foreach (var row in file.rows)
        {
            _rows[row.EnemyId] = row;
        }
    }

    public EnemyConfigRow GetById(string enemyId)
    {
        if (_rows.TryGetValue(enemyId, out var row))
            return row;
        throw new System.Collections.Generic.KeyNotFoundException($"EnemyConfig 未找到 EnemyId={enemyId}");
    }

    public bool TryGetById(string enemyId, out EnemyConfigRow row) => _rows.TryGetValue(enemyId, out row);

    public IReadOnlyDictionary<string, EnemyConfigRow> All => _rows;
}
