// <auto-generated>
// 由 DataTableGenerator 生成，请勿手动修改
// </auto-generated>

using System.Collections.Generic;
using Newtonsoft.Json;

public sealed class EventConfigRow
{
    /// <summary>事件唯一 ID，格式 event_&lt;type&gt;_&lt;序号&gt;</summary>
    public string EventId { get; set; }
    /// <summary>枚举：combat_event / choice_event / puzzle_event / merchant_event / boss_event / lore_event / curse_event</summary>
    public string EventType { get; set; }
    /// <summary>玩家可见名称（本地化 Key）</summary>
    public string DisplayName { get; set; }
    /// <summary>前置条件 JSON：{ minElapsedSec, minRoomCleared, requiredFlag }；空字符串=无条件</summary>
    public string TriggerCondition { get; set; }
    /// <summary>完成时发放基础金币；0=不发</summary>
    public int BaseRewardCoin { get; set; }
    /// <summary>额外掉落池 ID，引用 LootPoolConfig；空=无额外掉落</summary>
    public string RewardPoolId { get; set; }
    /// <summary>超时时间(s)；choice_event 填 20(v2.1)；-1=不超时(merchant_event)</summary>
    public float TimeoutSec { get; set; }
    /// <summary>仅 curse_event 用：施加的 Debuff ID；其余留空</summary>
    public string CurseDebuffId { get; set; }
    /// <summary>地图生成时随机选取事件类型的基础权重 (1–100)</summary>
    public int WeightBase { get; set; }
    /// <summary>同一 Run 内是否允许同一 EventId 重复出现</summary>
    public bool IsRepeatAllowed { get; set; }
}

public sealed class EventConfig : IDataTable
{
    readonly Dictionary<string, EventConfigRow> _rows = new();

    public void Load(string json)
    {
        var file = JsonConvert.DeserializeObject<DataTableFile<EventConfigRow>>(json);
        _rows.Clear();
        foreach (var row in file.rows)
        {
            _rows[row.EventId] = row;
        }
    }

    public EventConfigRow GetById(string eventId)
    {
        if (_rows.TryGetValue(eventId, out var row))
            return row;
        throw new KeyNotFoundException($"EventConfig 未找到 EventId={eventId}");
    }

    public bool TryGetById(string eventId, out EventConfigRow row) =>
        _rows.TryGetValue(eventId, out row);

    public IReadOnlyDictionary<string, EventConfigRow> All => _rows;
}
