// <auto-generated>
// 由 DataTableGenerator 生成，请勿手动修改
// </auto-generated>

using System.Collections.Generic;
using Newtonsoft.Json;

public sealed class ItemConfigRow
{
    /// <summary>物品唯一 ID，全局不重复</summary>
    public int ItemId { get; set; }
    /// <summary>枚举：Coin | InkBottle | RecipeShard | RecipeFull | Equipment | Antidote</summary>
    public string ItemType { get; set; }
    /// <summary>细分类型：颜料填 ColorId（1–7）；武器填品质（Common/Uncommon/Rare/Legendary）；其他留空</summary>
    public string SubType { get; set; }
    /// <summary>颜料档位：1=Basic / 2=Standard / 3=Premium；非颜料物品填 0</summary>
    public int Tier { get; set; }
    /// <summary>本地化显示名（中文，运行时替换为 LocalizationKey）</summary>
    public string DisplayName { get; set; }
    /// <summary>枚举：Common | Uncommon | Rare | Epic | Legendary</summary>
    public string Rarity { get; set; }
    /// <summary>单槽最大堆叠数；金币 = 9999，颜料 = 99，其他 = 1</summary>
    public int MaxStack { get; set; }
    /// <summary>基础定价（coin）；供商人 ShopStockConfig 引用计算实际价格</summary>
    public int BasePrice { get; set; }
    /// <summary>玩家出售时的回收比例（× BasePrice）；默认 0.4</summary>
    public float SellRatio { get; set; }
}

public sealed class ItemConfig : IDataTable
{
    readonly Dictionary<int, ItemConfigRow> _rows = new();

    public void Load(string json)
    {
        var file = JsonConvert.DeserializeObject<DataTableFile<ItemConfigRow>>(json);
        _rows.Clear();
        foreach (var row in file.rows)
        {
            _rows[row.ItemId] = row;
        }
    }

    public ItemConfigRow GetById(int itemId)
    {
        if (_rows.TryGetValue(itemId, out var row))
            return row;
        throw new KeyNotFoundException($"ItemConfig 未找到 ItemId={itemId}");
    }

    public bool TryGetById(int itemId, out ItemConfigRow row) => _rows.TryGetValue(itemId, out row);

    public IReadOnlyDictionary<int, ItemConfigRow> All => _rows;
}
