// <auto-generated>
// 由 DataTableGenerator 生成，请勿手动修改
// </auto-generated>

using System.Collections.Generic;
using Newtonsoft.Json;

public sealed class MerchantConfigRow
{
    /// <summary>商人展示槽位索引，范围 0~2（每局刷新时按 RefreshWeight 随机选定该槽武器）</summary>
    public int SlotIndex { get; set; }
    /// <summary>候选武器 ID，对应 WeaponConfig.WeaponId</summary>
    public string WeaponId { get; set; }
    /// <summary>购买所需金币（单位 coin），范围 [50, 200]</summary>
    public int GoldCost { get; set; }
    /// <summary>商人每局刷新时该候选被选中的概率权重（同 SlotIndex 内竞争）</summary>
    public int RefreshWeight { get; set; }
}

public sealed class MerchantConfig : IDataTable
{
    readonly List<MerchantConfigRow> _rows = new();

    public void Load(string json)
    {
        var file = JsonConvert.DeserializeObject<DataTableFile<MerchantConfigRow>>(json);
        _rows.Clear();
        foreach (var row in file.rows)
        {
            _rows.Add(row);
        }
    }

    /// <summary>取指定槽位的所有候选武器行（用于按 RefreshWeight 加权随机刷新）。</summary>
    public IReadOnlyList<MerchantConfigRow> GetBySlot(int slotIndex)
    {
        var list = new List<MerchantConfigRow>();
        foreach (var row in _rows)
        {
            if (row.SlotIndex == slotIndex)
                list.Add(row);
        }
        return list;
    }

    /// <summary>按 (slotIndex, weaponId) 取行（用于商人购买时反查 GoldCost）。</summary>
    public bool TryGet(int slotIndex, string weaponId, out MerchantConfigRow row)
    {
        foreach (var r in _rows)
        {
            if (r.SlotIndex == slotIndex && r.WeaponId == weaponId)
            {
                row = r;
                return true;
            }
        }
        row = null;
        return false;
    }

    public IReadOnlyList<MerchantConfigRow> Rows => _rows;
}
