// <auto-generated>
// 由 DataTableGenerator 生成，请勿手动修改
// </auto-generated>

using System.Collections.Generic;
using Newtonsoft.Json;

public sealed class SkillConfigRow
{
    /// <summary>唯一技能 ID，如 skill_fireball_01</summary>
    public string SkillId { get; set; }
    /// <summary>显示名称</summary>
    public string Name { get; set; }
    /// <summary>0=纯冷却 / 1=充能 / 2=蓄力释放</summary>
    public int ChargeModel { get; set; }
    /// <summary>冷却时长(s)，ChargeModel=0 时生效</summary>
    public float Cooldown { get; set; }
    /// <summary>最大充能层数，ChargeModel=1 时生效</summary>
    public int MaxCharges { get; set; }
    /// <summary>单层恢复时间(s)，ChargeModel=1 时生效</summary>
    public float ChargeRegenTime { get; set; }
    /// <summary>蓄力满充时长(s)，ChargeModel=2 时生效</summary>
    public float HoldDuration { get; set; }
    /// <summary>过载窗口时长(s)，ChargeModel=2 时生效</summary>
    public float OverchargeWindow { get; set; }
    /// <summary>预备帧 (60fps 基准)</summary>
    public int StartupFrames { get; set; }
    /// <summary>激活帧 (60fps 基准)</summary>
    public int ActiveFrames { get; set; }
    /// <summary>恢复帧 (60fps 基准)</summary>
    public int RecoveryFrames { get; set; }
    /// <summary>伤害倍率，乘以 BaseDamage</summary>
    public float DamageMul { get; set; }
    /// <summary>single / circle / line / cone</summary>
    public string HitShape { get; set; }
    /// <summary>命中范围半径(m)，single 时忽略</summary>
    public float HitRadius { get; set; }
    /// <summary>元素染色：Fire / Frost / Lightning / Holy / Nature / None</summary>
    public string Element { get; set; }
    /// <summary>Startup 帧内是否允许闪避取消</summary>
    public bool CancelableByDodge { get; set; }
    /// <summary>商人出售 ItemId，0 表示非商品</summary>
    public int ItemId { get; set; }
}

public sealed class SkillConfig : IDataTable
{
    readonly Dictionary<string, SkillConfigRow> _rows = new();

    public void Load(string json)
    {
        var file = JsonConvert.DeserializeObject<DataTableFile<SkillConfigRow>>(json);
        _rows.Clear();
        foreach (var row in file.rows)
        {
            _rows[row.SkillId] = row;
        }
    }

    public SkillConfigRow GetById(string skillId)
    {
        if (_rows.TryGetValue(skillId, out var row))
            return row;
        throw new KeyNotFoundException($"SkillConfig 未找到 SkillId={skillId}");
    }

    public bool TryGetById(string skillId, out SkillConfigRow row) => _rows.TryGetValue(skillId, out row);

    public IReadOnlyDictionary<string, SkillConfigRow> All => _rows;
}
