// <auto-generated>
// 由 DataTableGenerator 生成，请勿手动修改
// </auto-generated>

using System.Collections.Generic;
using Newtonsoft.Json;

public sealed class TattooPartConfigRow
{
    /// <summary>主键 1-6</summary>
    public int Id { get; set; }
    /// <summary>Head / Torso / LeftArm / RightArm / LeftLeg / RightLeg</summary>
    public string Name { get; set; }
    /// <summary>事件类名：AttackHitEvent / CritHitEvent / DamagedEvent / SkillCastEvent / DodgePressedEvent / MoveTickEvent</summary>
    public string TriggerEvent { get; set; }
    /// <summary>StatType enum 名</summary>
    public string ScaleStat { get; set; }
    /// <summary>None / Arms / Legs</summary>
    public string SymmetryGroup { get; set; }
    /// <summary>缩放系数</summary>
    public float ScaleFactor { get; set; }
    /// <summary>被动维度标签（暴击/抗性/技能/武器/闪避/移速）</summary>
    public string PassiveDimension { get; set; }
}

public sealed class TattooPartConfig : IDataTable
{
    readonly Dictionary<int, TattooPartConfigRow> _rows = new();

    public void Load(string json)
    {
        var file = JsonConvert.DeserializeObject<DataTableFile<TattooPartConfigRow>>(json);
        _rows.Clear();
        foreach (var row in file.rows)
        {
            _rows[row.Id] = row;
        }
    }

    public TattooPartConfigRow GetById(int id)
    {
        if (_rows.TryGetValue(id, out var row))
            return row;
        throw new KeyNotFoundException($"TattooPartConfig 未找到 Id={id}");
    }

    public bool TryGetById(int id, out TattooPartConfigRow row) => _rows.TryGetValue(id, out row);

    public IReadOnlyDictionary<int, TattooPartConfigRow> All => _rows;
}
