// <auto-generated>
// 由 DataTableGenerator 生成，请勿手动修改
// </auto-generated>

using System.Collections.Generic;
using Newtonsoft.Json;

public sealed class ThreeChoiceOptionConfigRow
{
    /// <summary>选项唯一 ID</summary>
    public string OptionId { get; set; }
    /// <summary>枚举：tattoo_recipe / pattern_recipe / weapon_upgrade / skill_upgrade / skill_acquire / coin_bonus / heal / one_time_scroll</summary>
    public string OptionType { get; set; }
    /// <summary>选项标题（本地化 Key）</summary>
    public string DisplayName { get; set; }
    /// <summary>选项描述（本地化 Key）</summary>
    public string DescKey { get; set; }
    /// <summary>内容引用：tattoo_recipe/pattern_recipe=配方ID；weapon_upgrade=升级配置ID；skill_upgrade=技能升级ID；skill_acquire=技能ID；其余为空</summary>
    public string ContentRef { get; set; }
    /// <summary>仅 skill_upgrade 用：目标技能槽编号，值域 {0, 1}；其余类型填 -1</summary>
    public int SkillSlot { get; set; }
    /// <summary>数值型内容（金币量/治疗量/百分比）；非数值型填 0</summary>
    public int ValueInt { get; set; }
    /// <summary>基础抽取权重 (1–100)</summary>
    public int WeightBase { get; set; }
    /// <summary>Build 联动加权 JSON：{ elementTag: bonusWeight }；与 Build 元素匹配时额外叠加</summary>
    public string WeightBuildBonus { get; set; }
    /// <summary>最早出现时间(s)；0=无限制</summary>
    public float MinRunElapsedSec { get; set; }
    /// <summary>同一 Run 内只能出现一次（pattern_recipe = true）</summary>
    public bool IsUnique { get; set; }
}

public sealed class ThreeChoiceOptionConfig : IDataTable
{
    readonly Dictionary<string, ThreeChoiceOptionConfigRow> _rows = new();
    // 按 OptionType 分组缓存（EventModule 高频访问）
    readonly Dictionary<string, List<ThreeChoiceOptionConfigRow>> _byType = new();

    public void Load(string json)
    {
        var file = JsonConvert.DeserializeObject<DataTableFile<ThreeChoiceOptionConfigRow>>(json);
        _rows.Clear();
        _byType.Clear();
        foreach (var row in file.rows)
        {
            _rows[row.OptionId] = row;
            if (!_byType.TryGetValue(row.OptionType, out var list))
            {
                list = new List<ThreeChoiceOptionConfigRow>();
                _byType[row.OptionType] = list;
            }
            list.Add(row);
        }
    }

    public ThreeChoiceOptionConfigRow GetById(string optionId)
    {
        if (_rows.TryGetValue(optionId, out var row))
            return row;
        throw new KeyNotFoundException($"ThreeChoiceOptionConfig 未找到 OptionId={optionId}");
    }

    public bool TryGetById(string optionId, out ThreeChoiceOptionConfigRow row) =>
        _rows.TryGetValue(optionId, out row);

    /// <summary>获取指定类型的所有选项（只读）。EventModule 抽签使用。</summary>
    public IReadOnlyList<ThreeChoiceOptionConfigRow> GetByType(string optionType)
    {
        if (_byType.TryGetValue(optionType, out var list))
            return list;
        return System.Array.Empty<ThreeChoiceOptionConfigRow>();
    }

    public IReadOnlyDictionary<string, ThreeChoiceOptionConfigRow> All => _rows;

    /// <summary>所有 OptionType 分组（只读）。供 EventModule InitAsync 缓存使用。</summary>
    public IReadOnlyDictionary<string, List<ThreeChoiceOptionConfigRow>> AllByType => _byType;
}
