// <auto-generated>
// 由 DataTableGenerator 生成，请勿手动修改
// </auto-generated>

using System.Collections.Generic;
using Newtonsoft.Json;

public sealed class UIFormConfigRow
{
    /// <summary>Form 唯一 ID</summary>
    public int Id { get; set; }
    /// <summary>Form C# class 名</summary>
    public string FormName { get; set; }
    /// <summary>相对于 Assets/Resources/Prefab/ 的路径（含子目录，不含扩展名）</summary>
    public string PrefabPath { get; set; }
    /// <summary>Canvas Sort Order：HUD=0，覆盖层=10，系统=20，全屏=30</summary>
    public int SortOrder { get; set; }
    /// <summary>是否实现 IExclusiveUIForm（覆盖层互斥）</summary>
    public bool IsExclusive { get; set; }
}

public sealed class UIFormConfig : IDataTable
{
    readonly Dictionary<int, UIFormConfigRow> _rows = new();

    public void Load(string json)
    {
        var file = JsonConvert.DeserializeObject<DataTableFile<UIFormConfigRow>>(json);
        _rows.Clear();
        foreach (var row in file.rows)
            _rows[row.Id] = row;
    }

    public UIFormConfigRow GetById(int id)
    {
        if (_rows.TryGetValue(id, out var row)) return row;
        throw new KeyNotFoundException($"UIFormConfig 未找到 Id={id}");
    }

    public bool TryGetById(int id, out UIFormConfigRow row) => _rows.TryGetValue(id, out row);

    public IReadOnlyDictionary<int, UIFormConfigRow> All => _rows;
}
