// <auto-generated>
// 由 DataTableGenerator 生成，请勿手动修改
// </auto-generated>

using System.Collections.Generic;
using Newtonsoft.Json;

public sealed class WeaponDropConfigRow
{
    /// <summary>主键，全局唯一掉落记录 ID</summary>
    public string DropId { get; set; }
    /// <summary>对应 WeaponConfig.WeaponId</summary>
    public string WeaponId { get; set; }
    /// <summary>枚举：Elite / Chest / Merchant</summary>
    public string DropSource { get; set; }
    /// <summary>同 DropSource 内加权随机权重，越高越易出</summary>
    public int Weight { get; set; }
    /// <summary>该武器最早可出现的房间序号（关卡进度门控，1=起始房）</summary>
    public int MinRoomIndex { get; set; }
    /// <summary>该武器最晚可出现的房间序号（10=最终Boss前一房）</summary>
    public int MaxRoomIndex { get; set; }
}

public sealed class WeaponDropConfig : IDataTable
{
    readonly Dictionary<string, WeaponDropConfigRow> _rows = new();
    readonly List<WeaponDropConfigRow> _all = new();

    public void Load(string json)
    {
        var file = JsonConvert.DeserializeObject<DataTableFile<WeaponDropConfigRow>>(json);
        _rows.Clear();
        _all.Clear();
        foreach (var row in file.rows)
        {
            _rows[row.DropId] = row;
            _all.Add(row);
        }
    }

    public WeaponDropConfigRow GetById(string dropId)
    {
        if (_rows.TryGetValue(dropId, out var row))
            return row;
        throw new KeyNotFoundException($"WeaponDropConfig 未找到 DropId={dropId}");
    }

    public bool TryGetById(string dropId, out WeaponDropConfigRow row) => _rows.TryGetValue(dropId, out row);

    public IReadOnlyDictionary<string, WeaponDropConfigRow> All => _rows;

    /// <summary>遍历用：按插入序的全量行（含同 DropSource 的多条）。</summary>
    public IReadOnlyList<WeaponDropConfigRow> Rows => _all;
}
