// <auto-generated>
// 由 DataTableGenerator 生成，请勿手动修改
// </auto-generated>

using System.Collections.Generic;
using Newtonsoft.Json;

public sealed class WeaponConfigRow
{
    /// <summary>主键，如 knife_basic / pistol_basic</summary>
    public string WeaponId { get; set; }
    /// <summary>显示名称</summary>
    public string Name { get; set; }
    /// <summary>Melee / Ranged / Special</summary>
    public string Class { get; set; }
    /// <summary>基础伤害，TattooModule scaleStat 基准</summary>
    public float BaseDamage { get; set; }
    /// <summary>AttackSpeedModifier，叠加到 PassiveStats.AttackSpeed</summary>
    public float AttackSpeed { get; set; }
    /// <summary>近战 Hitbox 球形半径（米），远程为最大有效距离</summary>
    public float Range { get; set; }
    /// <summary>蓄力伤害倍率，覆盖默认 1.5x</summary>
    public float ChargedMul { get; set; }
    /// <summary>远程武器对应飞行物 ID，近战留空</summary>
    public string ProjectileId { get; set; }
    /// <summary>稀有度 0=普通 1=精良 2=稀有 3=史诗</summary>
    public int Rarity { get; set; }
    /// <summary>-1=无限（近战），远程为弹匣容量</summary>
    public int MaxAmmo { get; set; }
    /// <summary>前摇帧数（60fps 基准）</summary>
    public int BaseStartup { get; set; }
    /// <summary>伤害帧数（Hitbox 开启区间）</summary>
    public int BaseActive { get; set; }
    /// <summary>后摇帧数</summary>
    public int BaseRecovery { get; set; }
    /// <summary>true=需蓄力才激活伤害判定（弓）</summary>
    public bool RequiresCharge { get; set; }
    /// <summary>change#20: 鼠标射击半角(度) 0=Raycast严格 / 180=自动锁定 / 中间=SphereCast</summary>
    public float AimSpreadHalfDeg { get; set; }
    /// <summary>change#20: 普攻 trait，引用 WeaponTraitConfig.TraitId</summary>
    public string NormalTraitId { get; set; }
    /// <summary>change#20: 蓄力 trait，引用 WeaponTraitConfig.TraitId</summary>
    public string ChargedTraitId { get; set; }
    /// <summary>change#20: 武器 prefab Resources 路径（不含扩展名）</summary>
    public string WeaponPrefabPath { get; set; }
}

public sealed class WeaponConfig : IDataTable
{
    readonly Dictionary<string, WeaponConfigRow> _rows = new();

    public void Load(string json)
    {
        var file = JsonConvert.DeserializeObject<DataTableFile<WeaponConfigRow>>(json);
        _rows.Clear();
        foreach (var row in file.rows)
        {
            _rows[row.WeaponId] = row;
        }
    }

    public WeaponConfigRow GetById(string weaponId)
    {
        if (_rows.TryGetValue(weaponId, out var row))
            return row;
        throw new KeyNotFoundException($"WeaponConfig 未找到 WeaponId={weaponId}");
    }

    public bool TryGetById(string weaponId, out WeaponConfigRow row) =>
        _rows.TryGetValue(weaponId, out row);

    public IReadOnlyDictionary<string, WeaponConfigRow> All => _rows;
}
