// <auto-generated>
// 由 DataTableGenerator 生成，请勿手动修改
// </auto-generated>

using System.Collections.Generic;
using Newtonsoft.Json;

public sealed class WeaponTraitConfigRow
{
    /// <summary>主键，如 trait_quickslash / trait_pierce</summary>
    public string TraitId { get; set; }
    /// <summary>显示名称</summary>
    public string Name { get; set; }
    /// <summary>UI tooltip</summary>
    public string Description { get; set; }
    /// <summary>枚举占位：Status / Pierce / Stun / Chain / Explosive / MultiShot / Pull / Quick</summary>
    public string EffectType { get; set; }
    /// <summary>主参数（数值由 gd-system 阶段 H 平衡）</summary>
    public float EffectParam1 { get; set; }
    /// <summary>副参数</summary>
    public float EffectParam2 { get; set; }
}

public sealed class WeaponTraitConfig : IDataTable
{
    readonly Dictionary<string, WeaponTraitConfigRow> _rows = new();

    public void Load(string json)
    {
        var file = JsonConvert.DeserializeObject<DataTableFile<WeaponTraitConfigRow>>(json);
        _rows.Clear();
        foreach (var row in file.rows)
        {
            _rows[row.TraitId] = row;
        }
    }

    public WeaponTraitConfigRow GetById(string traitId)
    {
        if (_rows.TryGetValue(traitId, out var row))
            return row;
        throw new KeyNotFoundException($"WeaponTraitConfig 未找到 TraitId={traitId}");
    }

    public bool TryGetById(string traitId, out WeaponTraitConfigRow row) =>
        _rows.TryGetValue(traitId, out row);

    public IReadOnlyDictionary<string, WeaponTraitConfigRow> All => _rows;
}
