using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.IO;
using System.Text;
using Newtonsoft.Json.Linq;
using UnityEditor;
using UnityEngine;

public static class DataTableGenerator
{
    const string Header = "// <auto-generated>\n// 由 DataTableGenerator 生成，请勿手动修改\n// </auto-generated>\n\n";

    static readonly HashSet<string> BaseTypes = new()
    {
        "int", "float", "double", "string", "bool"
    };

    /// <summary>
    /// 支持：基础类型、任意维度数组（T[]、T[][]...）、Dictionary&lt;K,V&gt;（K 为基础类型，V 可递归为以上任意类型）
    /// </summary>
    static bool IsSupportedType(string type)
    {
        if (BaseTypes.Contains(type))
            return true;

        if (type.EndsWith("[]"))
            return IsSupportedType(type[..^2]);

        if (type.StartsWith("Dictionary<") && type.EndsWith(">"))
        {
            var inner = type[(type.IndexOf('<') + 1)..^1];
            var commaIndex = inner.IndexOf(',');
            if (commaIndex < 0)
                return false;

            var keyType = inner[..commaIndex].Trim();
            var valueType = inner[(commaIndex + 1)..].Trim();
            return BaseTypes.Contains(keyType) && IsSupportedType(valueType);
        }

        return false;
    }

    struct TableSchema
    {
        public string FileName;
        public string TableName;
        public JArray Fields;
    }

    [MenuItem("Tools/DataTable/生成全部配置表代码")]
    public static void GenerateAll()
    {
        var sourceDir = Path.Combine(Application.dataPath, "Resources/DataTable");
        var outputDir = Path.Combine(Application.dataPath, "Scripts/DataTable");

        if (!Directory.Exists(sourceDir))
        {
            FrameworkLogger.Error("DataTableGenerator", $"Action=GenerateAll 源目录不存在 Path={sourceDir}");
            return;
        }

        Directory.CreateDirectory(outputDir);

        var tables = new List<TableSchema>();
        foreach (var jsonPath in Directory.GetFiles(sourceDir, "*.json"))
        {
            var fileName = Path.GetFileNameWithoutExtension(jsonPath);
            var root = JObject.Parse(File.ReadAllText(jsonPath));

            var tableName = root["table"]?.ToString();
            if (tableName != fileName)
                Fail($"配置表 {fileName}.json 的 table 字段 (\"{tableName}\") 与文件名不一致");

            var fields = root["fields"] as JArray;
            if (fields == null || fields.Count == 0)
                Fail($"配置表 {fileName}.json 缺少 fields 定义");

            ValidateFields(fileName, fields);

            tables.Add(new TableSchema { FileName = fileName, TableName = tableName, Fields = fields });
        }

        foreach (var table in tables)
        {
            var source = Header + "using System.Collections.Generic;\nusing Newtonsoft.Json;\n\n"
                + GenerateRowClass(table.TableName, table.Fields)
                + GenerateTableClass(table.TableName);

            File.WriteAllText(Path.Combine(outputDir, $"{table.TableName}.cs"), source);

            FrameworkLogger.Info("DataTableGenerator",
                $"Action=TableGenerated Table={table.TableName} File={table.FileName}.json");
        }

        File.WriteAllText(Path.Combine(outputDir, "DataTableRegistry.cs"), GenerateRegistry(tables));

        AssetDatabase.Refresh();

        FrameworkLogger.Info("DataTableGenerator", $"Action=GenerateAllCompleted Count={tables.Count}");
    }

    static void ValidateFields(string fileName, JArray fields)
    {
        var first = fields[0];
        if (first["name"]?.ToString() != "Id" || first["type"]?.ToString() != "int")
            Fail($"配置表 {fileName}.json 的 fields[0] 必须是 {{ name: \"Id\", type: \"int\" }}");

        foreach (var field in fields)
        {
            var name = field["name"]?.ToString();
            var type = field["type"]?.ToString();

            if (string.IsNullOrEmpty(name) || !CodeGenerator.IsValidLanguageIndependentIdentifier(name))
                Fail($"配置表 {fileName}.json 字段名非法: \"{name}\"");

            if (!IsSupportedType(type))
                Fail($"配置表 {fileName}.json 字段 {name} 的类型不受支持: \"{type}\"");
        }
    }

    static string GenerateRowClass(string tableName, JArray fields)
    {
        var sb = new StringBuilder();
        sb.AppendLine($"public sealed class {tableName}Row");
        sb.AppendLine("{");
        foreach (var field in fields)
        {
            var name = field["name"]!.ToString();
            var type = field["type"]!.ToString();
            var desc = field["desc"]?.ToString();

            if (!string.IsNullOrEmpty(desc))
                sb.AppendLine($"    /// <summary>{desc}</summary>");
            sb.AppendLine($"    public {type} {name} {{ get; set; }}");
        }
        sb.AppendLine("}");
        sb.AppendLine();
        return sb.ToString();
    }

    static string GenerateTableClass(string tableName)
    {
        return $@"public sealed class {tableName} : IDataTable
{{
    readonly Dictionary<int, {tableName}Row> _rows = new();

    public void Load(string json)
    {{
        var file = JsonConvert.DeserializeObject<DataTableFile<{tableName}Row>>(json);
        _rows.Clear();
        foreach (var row in file.rows)
        {{
            _rows[row.Id] = row;
        }}
    }}

    public {tableName}Row GetById(int id)
    {{
        if (_rows.TryGetValue(id, out var row))
            return row;
        throw new KeyNotFoundException($""{tableName} 未找到 Id={{id}}"");
    }}

    public bool TryGetById(int id, out {tableName}Row row) => _rows.TryGetValue(id, out row);

    public IReadOnlyDictionary<int, {tableName}Row> All => _rows;
}}
";
    }

    static string GenerateRegistry(List<TableSchema> tables)
    {
        var sb = new StringBuilder();
        sb.Append(Header);
        sb.AppendLine("using System;");
        sb.AppendLine();
        sb.AppendLine("public static class DataTableRegistry");
        sb.AppendLine("{");
        sb.AppendLine("    public static readonly DataTableEntry[] Entries =");
        sb.AppendLine("    {");
        foreach (var table in tables)
            sb.AppendLine($"        new DataTableEntry(\"{table.FileName}\", typeof({table.TableName})),");
        sb.AppendLine("    };");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("public readonly struct DataTableEntry");
        sb.AppendLine("{");
        sb.AppendLine("    public readonly string FileName;");
        sb.AppendLine("    public readonly Type TableType;");
        sb.AppendLine();
        sb.AppendLine("    public DataTableEntry(string fileName, Type tableType)");
        sb.AppendLine("    {");
        sb.AppendLine("        FileName = fileName;");
        sb.AppendLine("        TableType = tableType;");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }

    static void Fail(string message)
    {
        FrameworkLogger.Error("DataTableGenerator", message);
        throw new InvalidOperationException(message);
    }
}
