//------------------------------------------------------------
//------------------------------------------------------------
// This file is generated by the GF_X DataTable workflow.
// Generation time: __DATA_TABLE_CREATE_TIME__
//------------------------------------------------------------

using GameFramework;
using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using UnityEngine;
using UnityGameFramework.Runtime;
#if ENABLE_OBFUZ
[Obfuz.ObfuzIgnore(Obfuz.ObfuzScope.TypeName | Obfuz.ObfuzScope.MethodName)]
#endif
/// <summary>
/// World-clock encounter schedules generated from Business/EncounterSpawnConfig.
/// </summary>
public class EncounterSpawnConfig : DataRowBase
{
    private int m_Id = 0;

    /// <summary>
    /// GF_X numeric row id.
    /// </summary>
    public override int Id
    {
        get { return m_Id; }
    }

    /// <summary>
    /// Stable encounter schedule id.
    /// </summary>
    public string EncounterId
    {
        get;
        private set;
    }

    /// <summary>
    /// Map theme id.
    /// </summary>
    public string ThemeId
    {
        get;
        private set;
    }

    /// <summary>
    /// Comma-separated PCG anchor roles.
    /// </summary>
    public string ZoneRoles
    {
        get;
        private set;
    }

    /// <summary>
    /// Comma-separated EnemyConfig pool ids.
    /// </summary>
    public string EnemyPoolIds
    {
        get;
        private set;
    }

    /// <summary>
    /// World-time start in seconds.
    /// </summary>
    public float StartTime
    {
        get;
        private set;
    }

    /// <summary>
    /// World-time end in seconds; zero means no end.
    /// </summary>
    public float EndTime
    {
        get;
        private set;
    }

    /// <summary>
    /// Initial or minimum scheduled count.
    /// </summary>
    public int InitialCount
    {
        get;
        private set;
    }

    /// <summary>
    /// Simultaneous active cap.
    /// </summary>
    public int ActiveCap
    {
        get;
        private set;
    }

    /// <summary>
    /// Total per-run cap.
    /// </summary>
    public int TotalCap
    {
        get;
        private set;
    }

    /// <summary>
    /// Minimum wave size.
    /// </summary>
    public int WaveMin
    {
        get;
        private set;
    }

    /// <summary>
    /// Maximum wave size.
    /// </summary>
    public int WaveMax
    {
        get;
        private set;
    }

    /// <summary>
    /// Wave interval seconds.
    /// </summary>
    public float WaveInterval
    {
        get;
        private set;
    }

    /// <summary>
    /// Minimum distance from active participants.
    /// </summary>
    public float MinParticipantDistance
    {
        get;
        private set;
    }

    /// <summary>
    /// Minimum same-wave spacing.
    /// </summary>
    public float MinSpacing
    {
        get;
        private set;
    }

    /// <summary>
    /// Selection weight.
    /// </summary>
    public int Weight
    {
        get;
        private set;
    }

    /// <summary>
    /// Execute at most once.
    /// </summary>
    public bool Unique
    {
        get;
        private set;
    }

    public override bool ParseDataRow(string dataRowString, object userData)
    {
        string[] columnStrings = dataRowString.Split(DataTableExtension.DataSplitSeparators);
        for (int i = 0; i < columnStrings.Length; i++)
        {
            columnStrings[i] = columnStrings[i].Trim(DataTableExtension.DataTrimSeparators);
        }

        int index = 0;
        index++;
        m_Id = int.Parse(columnStrings[index++]);
        index++;
        EncounterId = columnStrings[index++];
        ThemeId = columnStrings[index++];
        ZoneRoles = columnStrings[index++];
        EnemyPoolIds = columnStrings[index++];
        StartTime = float.Parse(columnStrings[index++]);
        EndTime = float.Parse(columnStrings[index++]);
        InitialCount = int.Parse(columnStrings[index++]);
        ActiveCap = int.Parse(columnStrings[index++]);
        TotalCap = int.Parse(columnStrings[index++]);
        WaveMin = int.Parse(columnStrings[index++]);
        WaveMax = int.Parse(columnStrings[index++]);
        WaveInterval = float.Parse(columnStrings[index++]);
        MinParticipantDistance = float.Parse(columnStrings[index++]);
        MinSpacing = float.Parse(columnStrings[index++]);
        Weight = int.Parse(columnStrings[index++]);
        Unique = bool.Parse(columnStrings[index++]);

        return true;
    }

    public override bool ParseDataRow(byte[] dataRowBytes, int startIndex, int length, object userData)
    {
        using (MemoryStream memoryStream = new MemoryStream(dataRowBytes, startIndex, length, false))
        {
            using (BinaryReader binaryReader = new BinaryReader(memoryStream, Encoding.UTF8))
            {
                m_Id = binaryReader.Read7BitEncodedInt32();
                EncounterId = binaryReader.ReadString();
                ThemeId = binaryReader.ReadString();
                ZoneRoles = binaryReader.ReadString();
                EnemyPoolIds = binaryReader.ReadString();
                StartTime = binaryReader.ReadSingle();
                EndTime = binaryReader.ReadSingle();
                InitialCount = binaryReader.Read7BitEncodedInt32();
                ActiveCap = binaryReader.Read7BitEncodedInt32();
                TotalCap = binaryReader.Read7BitEncodedInt32();
                WaveMin = binaryReader.Read7BitEncodedInt32();
                WaveMax = binaryReader.Read7BitEncodedInt32();
                WaveInterval = binaryReader.ReadSingle();
                MinParticipantDistance = binaryReader.ReadSingle();
                MinSpacing = binaryReader.ReadSingle();
                Weight = binaryReader.Read7BitEncodedInt32();
                Unique = binaryReader.ReadBoolean();
            }
        }

        return true;
    }
}
