//------------------------------------------------------------
//------------------------------------------------------------
// This file is generated by the GF_X DataTable workflow.
// Generation time: __DATA_TABLE_CREATE_TIME__
//------------------------------------------------------------

using GameFramework;
using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using UnityEngine;
using UnityGameFramework.Runtime;
#if ENABLE_OBFUZ
[Obfuz.ObfuzIgnore(Obfuz.ObfuzScope.TypeName | Obfuz.ObfuzScope.MethodName)]
#endif
/// <summary>
/// Reusable native Enemy abilities generated from Business/EnemyAbilityConfig.
/// </summary>
public class EnemyAbilityConfig : DataRowBase
{
    private int m_Id = 0;

    /// <summary>
    /// GF_X numeric row id.
    /// </summary>
    public override int Id
    {
        get { return m_Id; }
    }

    /// <summary>
    /// Stable reusable enemy ability id.
    /// </summary>
    public string AbilityId
    {
        get;
        private set;
    }

    /// <summary>
    /// Reusable ability executor type.
    /// </summary>
    public string AbilityType
    {
        get;
        private set;
    }

    /// <summary>
    /// Cast range in meters.
    /// </summary>
    public float Range
    {
        get;
        private set;
    }

    /// <summary>
    /// Area radius in meters.
    /// </summary>
    public float Radius
    {
        get;
        private set;
    }

    /// <summary>
    /// Cooldown seconds.
    /// </summary>
    public float Cooldown
    {
        get;
        private set;
    }

    /// <summary>
    /// Windup seconds.
    /// </summary>
    public float Windup
    {
        get;
        private set;
    }

    /// <summary>
    /// Active window seconds.
    /// </summary>
    public float Active
    {
        get;
        private set;
    }

    /// <summary>
    /// Recovery seconds.
    /// </summary>
    public float Recovery
    {
        get;
        private set;
    }

    /// <summary>
    /// Base damage multiplier.
    /// </summary>
    public float DamageMultiplier
    {
        get;
        private set;
    }

    /// <summary>
    /// Optional status id.
    /// </summary>
    public string StatusId
    {
        get;
        private set;
    }

    /// <summary>
    /// Status chance in range 0 through 1.
    /// </summary>
    public float StatusChance
    {
        get;
        private set;
    }

    /// <summary>
    /// Optional summoned EnemyConfig id.
    /// </summary>
    public string SummonEnemyId
    {
        get;
        private set;
    }

    /// <summary>
    /// Requested summon count.
    /// </summary>
    public int SummonCount
    {
        get;
        private set;
    }

    /// <summary>
    /// Optional VFX cue id.
    /// </summary>
    public string VfxId
    {
        get;
        private set;
    }

    /// <summary>
    /// Optional audio cue id.
    /// </summary>
    public string AudioCueId
    {
        get;
        private set;
    }

    /// <summary>
    /// Compact executor parameters JSON.
    /// </summary>
    public string ParametersJson
    {
        get;
        private set;
    }

    public override bool ParseDataRow(string dataRowString, object userData)
    {
        string[] columnStrings = dataRowString.Split(DataTableExtension.DataSplitSeparators);
        for (int i = 0; i < columnStrings.Length; i++)
        {
            columnStrings[i] = columnStrings[i].Trim(DataTableExtension.DataTrimSeparators);
        }

        int index = 0;
        index++;
        m_Id = int.Parse(columnStrings[index++]);
        index++;
        AbilityId = columnStrings[index++];
        AbilityType = columnStrings[index++];
        Range = float.Parse(columnStrings[index++]);
        Radius = float.Parse(columnStrings[index++]);
        Cooldown = float.Parse(columnStrings[index++]);
        Windup = float.Parse(columnStrings[index++]);
        Active = float.Parse(columnStrings[index++]);
        Recovery = float.Parse(columnStrings[index++]);
        DamageMultiplier = float.Parse(columnStrings[index++]);
        StatusId = columnStrings[index++];
        StatusChance = float.Parse(columnStrings[index++]);
        SummonEnemyId = columnStrings[index++];
        SummonCount = int.Parse(columnStrings[index++]);
        VfxId = columnStrings[index++];
        AudioCueId = columnStrings[index++];
        ParametersJson = columnStrings[index++];

        return true;
    }

    public override bool ParseDataRow(byte[] dataRowBytes, int startIndex, int length, object userData)
    {
        using (MemoryStream memoryStream = new MemoryStream(dataRowBytes, startIndex, length, false))
        {
            using (BinaryReader binaryReader = new BinaryReader(memoryStream, Encoding.UTF8))
            {
                m_Id = binaryReader.Read7BitEncodedInt32();
                AbilityId = binaryReader.ReadString();
                AbilityType = binaryReader.ReadString();
                Range = binaryReader.ReadSingle();
                Radius = binaryReader.ReadSingle();
                Cooldown = binaryReader.ReadSingle();
                Windup = binaryReader.ReadSingle();
                Active = binaryReader.ReadSingle();
                Recovery = binaryReader.ReadSingle();
                DamageMultiplier = binaryReader.ReadSingle();
                StatusId = binaryReader.ReadString();
                StatusChance = binaryReader.ReadSingle();
                SummonEnemyId = binaryReader.ReadString();
                SummonCount = binaryReader.Read7BitEncodedInt32();
                VfxId = binaryReader.ReadString();
                AudioCueId = binaryReader.ReadString();
                ParametersJson = binaryReader.ReadString();
            }
        }

        return true;
    }
}
