//------------------------------------------------------------
//------------------------------------------------------------
// This file is generated by the GF_X DataTable workflow.
// Generation time: __DATA_TABLE_CREATE_TIME__
//------------------------------------------------------------

using GameFramework;
using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using UnityEngine;
using UnityGameFramework.Runtime;
#if ENABLE_OBFUZ
[Obfuz.ObfuzIgnore(Obfuz.ObfuzScope.TypeName | Obfuz.ObfuzScope.MethodName)]
#endif
/// <summary>
/// Independent public Enemy loot generated from Business/EnemyLootConfig.
/// </summary>
public class EnemyLootConfig : DataRowBase
{
    private int m_Id = 0;

    /// <summary>
    /// GF_X numeric row id.
    /// </summary>
    public override int Id
    {
        get { return m_Id; }
    }

    /// <summary>
    /// Stable loot entry id.
    /// </summary>
    public string LootEntryId
    {
        get;
        private set;
    }

    /// <summary>
    /// Enemy loot table id.
    /// </summary>
    public string LootTableId
    {
        get;
        private set;
    }

    /// <summary>
    /// Item, weapon or recipe id.
    /// </summary>
    public string ItemId
    {
        get;
        private set;
    }

    /// <summary>
    /// Coin, Item, Paint, Weapon, Equipment or Recipe.
    /// </summary>
    public string RewardType
    {
        get;
        private set;
    }

    /// <summary>
    /// Minimum stack count.
    /// </summary>
    public int MinCount
    {
        get;
        private set;
    }

    /// <summary>
    /// Maximum stack count.
    /// </summary>
    public int MaxCount
    {
        get;
        private set;
    }

    /// <summary>
    /// Weighted-roll weight.
    /// </summary>
    public int Weight
    {
        get;
        private set;
    }

    /// <summary>
    /// Always emitted.
    /// </summary>
    public bool Guaranteed
    {
        get;
        private set;
    }

    /// <summary>
    /// Enemy tier filter.
    /// </summary>
    public string TierFilter
    {
        get;
        private set;
    }

    /// <summary>
    /// Enemy theme id.
    /// </summary>
    public string ThemeId
    {
        get;
        private set;
    }

    public override bool ParseDataRow(string dataRowString, object userData)
    {
        string[] columnStrings = dataRowString.Split(DataTableExtension.DataSplitSeparators);
        for (int i = 0; i < columnStrings.Length; i++)
        {
            columnStrings[i] = columnStrings[i].Trim(DataTableExtension.DataTrimSeparators);
        }

        int index = 0;
        index++;
        m_Id = int.Parse(columnStrings[index++]);
        index++;
        LootEntryId = columnStrings[index++];
        LootTableId = columnStrings[index++];
        ItemId = columnStrings[index++];
        RewardType = columnStrings[index++];
        MinCount = int.Parse(columnStrings[index++]);
        MaxCount = int.Parse(columnStrings[index++]);
        Weight = int.Parse(columnStrings[index++]);
        Guaranteed = bool.Parse(columnStrings[index++]);
        TierFilter = columnStrings[index++];
        ThemeId = columnStrings[index++];

        return true;
    }

    public override bool ParseDataRow(byte[] dataRowBytes, int startIndex, int length, object userData)
    {
        using (MemoryStream memoryStream = new MemoryStream(dataRowBytes, startIndex, length, false))
        {
            using (BinaryReader binaryReader = new BinaryReader(memoryStream, Encoding.UTF8))
            {
                m_Id = binaryReader.Read7BitEncodedInt32();
                LootEntryId = binaryReader.ReadString();
                LootTableId = binaryReader.ReadString();
                ItemId = binaryReader.ReadString();
                RewardType = binaryReader.ReadString();
                MinCount = binaryReader.Read7BitEncodedInt32();
                MaxCount = binaryReader.Read7BitEncodedInt32();
                Weight = binaryReader.Read7BitEncodedInt32();
                Guaranteed = binaryReader.ReadBoolean();
                TierFilter = binaryReader.ReadString();
                ThemeId = binaryReader.ReadString();
            }
        }

        return true;
    }
}
