// <auto-generated-manual>
// Assets/Scripts/Events/SettingsEvents.cs
// 设置模块事件定义。
// </auto-generated-manual>

/// <summary>
/// 设置已提交并写盘后发布。
/// Commit() 写盘成功后 EventBus.Publish 触发。
/// 未来需要响应设置变化的模块（UI 主题、HUD 字号等）订阅此事件。
/// </summary>
public readonly struct SettingsAppliedEvent
{
    public readonly SettingsData Data;

    public SettingsAppliedEvent(SettingsData data)
    {
        Data = data;
    }
}
